# Generated by Django 5.0.7 on 2024-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image_data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='WardrobeImage',
        ),
    ]
